### PR TITLE
Fix: Added import id for YNAB

### LINKED ISSUE #625: YNAB transaction reinserted if payee has changed
**Describe the bug**
When loading information from Leumi to YNAB, if the user changed the payee in YNAB, the transaction is reinserted with the original payee on the next run

**To Reproduce**

1. Setup Leumi account
2. Setup YNAB as the output application
3. Run
4. Change a payee name in a transaction in YNAB
5. Re-run

**Expected behavior**
No change in YNAB app (No new transaction is added)

**Actual behavior**
A new transaction is added where the payee name has changed

### PR DESCRIPTION
**Pull request by abirstolov**
In order to avoid duplicate inserted when a payee is changed, an import_id is added to the YNAB transaction

Fix #625 

## Summary by CodeRabbit

- **New Features**
	- Enhanced transaction handling with the introduction of a new property for import IDs.
	- Added a new function to generate import IDs based on transaction details.
	- Introduced a function to compare transactions based on their import IDs.

- **Bug Fixes**
	- Improved error handling in transaction creation to notify users when no transactions exist.

- **Tests**
	- Added a new test case for the `isSameTransaction` function to verify behavior with different payees.

### CODE REVIEW

File: packages/main/src/backend/export/outputVendors/ynab/ynab.ts [hunk 1]
```diff
@@ -196,7 +204,8 @@ export function isSameTransaction(
     Math.abs(transactionToCreate.amount - transactionFromYnab.amount) < 1000 &&
     // In a transfer transaction the payee name changes, but we still consider this the same transaction
     (areStringsEqualIgnoreCaseAndWhitespace(transactionToCreate.payee_name, transactionFromYnab.payee_name) ||
-      isATransferTransaction)
+      isATransferTransaction ||
+      isSameImportId(transactionToCreate, transactionFromYnab))
```
Comment (baruchiro) [inline packages/main/src/backend/export/outputVendors/ynab/ynab.ts:208]: This `return` condition becomes very complicated.

Could you break it into variables to make it more readable?

For example, take the `()` part to `sameTransactionDifferentPayeeName = ...`

File: packages/main/src/backend/export/outputVendors/ynab/ynab.ts [hunk 2]
```diff
@@ -196,7 +204,8 @@ export function isSameTransaction(
     Math.abs(transactionToCreate.amount - transactionFromYnab.amount) < 1000 &&
     // In a transfer transaction the payee name changes, but we still consider this the same transaction
```
Comment (baruchiro) [inline packages/main/src/backend/export/outputVendors/ynab/ynab.ts:205]: I see someone already tried to support your case by the comment:

> In a transfer transaction the payee name changes, but we still consider this the same transaction

**Review by baruchiro — COMMENTED** [review]
@brafdlog Please comment, I'm not familiar with YNAB

File: packages/main/src/backend/export/outputVendors/ynab/ynab.ts [hunk 3]
```diff
@@ -119,12 +119,20 @@ function convertTransactionToYnabFormat(originalTransaction: EnrichedTransaction
...
   };
 }
 
+function buildImportId(transaction: EnrichedTransaction): string {
+  return `${transaction.date.substring(0, 10)}${transaction.chargedAmount}${transaction.description}`.substring(
+    0,
+    MAX_YNAB_IMPORT_ID_LENGTH,
+  );
+}
+
```
[the remark this answers is not in the document]
Comment (abirstolov) [reply packages/main/src/backend/export/outputVendors/ynab/ynab.ts:135]: because YNAB _import_id_ is 36 characters max and should be unique
`calculateTransactionHash` is variable length and truncated will miss some information

File: packages/main/src/backend/export/outputVendors/ynab/ynab.ts (hunk 2 above)
Comment (abirstolov) [reply packages/main/src/backend/export/outputVendors/ynab/ynab.ts:205]: It's a different case, my condition is not referring a transfer transaction

File: packages/main/src/backend/export/outputVendors/ynab/ynab.ts (hunk 1 above)
Comment (abirstolov) [reply packages/main/src/backend/export/outputVendors/ynab/ynab.ts]: Done

File: packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts [hunk 4]
```diff
@@ -6,6 +6,42 @@ import * as ynab from './ynab';
...
+        account_id: 'SOME_ACCOUNT_ID',
+        account_name: 'My great account',
+        payee_id: 'fd7f187c-0633-434f-aaxe-1fevd68492cb',
+        payee_name: 'שיק',
+        category_id: null,
+        category_name: null,
+        transfer_account_id: null,
+        transfer_transaction_id: null,
+        matched_transaction_id: null,
+        import_id: '2019-06-27-1000000',
```
[the remark this answers is not in the document]
Comment (abirstolov) [reply packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts]: I've added a description

File: packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts [hunk 5]
```diff
@@ -6,6 +6,42 @@ import * as ynab from './ynab';
 import ClearedEnum = SaveTransaction.ClearedEnum;
 
 describe('ynab', () => {
+  describe('isSameTransaction(Payee changed)', () => {
+    test('Two transactions with different payee names should be considered the same if they have the same import id', () => {
+      const transferTransactionFromYnab: TransactionDetail = {
```
Comment (brafdlog) [inline packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts:11]: Rename as this is not a tranfer transaction
```suggestion
      const differentPayeeTransactionFromYnab: TransactionDetail = {
```

File: packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts [hunk 6]
```diff
@@ -6,6 +6,42 @@ import * as ynab from './ynab';
 import ClearedEnum = SaveTransaction.ClearedEnum;
 
 describe('ynab', () => {
+  describe('isSameTransaction(Payee changed)', () => {
```
Comment (brafdlog) [inline packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts:9]: I suggest to nest this under the describe for isSameTransaction.
So there is a top level describe for all isSameTransaction tests

**Review by brafdlog — COMMENTED** [review]
Looks good, thanks @abirstolov 
See comments

File: packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts (hunk 5 above)
Comment (abirstolov) [reply packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts]: Agreed, done.

File: packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts (hunk 6 above)
Comment (abirstolov) [reply packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts]: Agreed

**Comment by brafdlog** [comment]
@abirstolov did you check this version locally to see that it doesn't create duplicates of existing transactions?
Logically it shouldn't, but I want a sanity check before merging

**Comment by abirstolov** [comment]
> @abirstolov did you check this version locally to see that it doesn't create duplicates of existing transactions? Logically it shouldn't, but I want a sanity check before merging

**Comment by baruchiro** [comment]
@abirstolov if you need any help with GitHub talk with us on [Discord](https://discord.gg/XWWg7xvJyS)

**Comment by abirstolov** [comment]
@baruchiro I have tested that case, for the same transaction with a different payee - it didn't add a duplicate, and for a different transaction it did add.
